# Generated by Django 5.2.10 on 2026-02-06 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('Freshman', 1), ('Sophomore', 2), ('Junior', 3), ('Senior', 4)], max_length=100)),
                ('pass_apps', models.BooleanField()),
                ('pass_first', models.BooleanField()),
                ('pass_second', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('club_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('Short', 'SHORT'), ('Long', 'LONG'), ('Multi-Select', 'MULTI-SELECT'), ('File', 'FILE')], max_length=100)),
                ('prompt', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.applicationformmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationSubmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.applicantmodel')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.applicationformmodel')),
            ],
            options={
                'unique_together': {('application', 'applicant')},
            },
        ),
        migrations.AddField(
            model_name='applicationformmodel',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clubmodel'),
        ),
        migrations.AddField(
            model_name='applicantmodel',
            name='club_association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clubmodel'),
        ),
        migrations.CreateModel(
            name='ApplicationAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.applicationquestionmodel')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.applicationsubmissionmodel')),
            ],
            options={
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
