# Generated by Django 5.2.10 on 2026-02-07 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsubmissionmodel',
            name='status',
            field=models.CharField(choices=[(1, 'Draft'), (2, 'Submitted')], default='Submitted', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicantmodel',
            name='pass_apps',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicantmodel',
            name='pass_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicantmodel',
            name='pass_second',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicantmodel',
            name='year',
            field=models.CharField(choices=[(1, 'Freshman'), (2, 'Sophomore'), (3, 'Junior'), (4, 'Senior')], max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationquestionmodel',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.applicationformmodel'),
        ),
    ]
