# Generated by Django 5.2.10 on 2026-02-07 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_applicationsubmissionmodel_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationsubmissionmodel',
            old_name='application',
            new_name='form',
        ),
        migrations.AlterUniqueTogether(
            name='applicationsubmissionmodel',
            unique_together={('form', 'applicant')},
        ),
    ]
