# Generated by Django 5.2.10 on 2026-02-07 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_applicantmodel_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsubmissionmodel',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.applicantmodel'),
        ),
    ]
