# Generated by Django 5.2.10 on 2026-02-07 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_applicationsubmissionmodel_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsubmissionmodel',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='api.applicantmodel'),
        ),
    ]
