# Generated by Django 5.2.10 on 2026-02-07 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_applicationsubmissionmodel_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantmodel',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationanswermodel',
            name='answer',
        ),
        migrations.AddField(
            model_name='applicationanswermodel',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to='answers/'),
        ),
        migrations.AddField(
            model_name='applicationanswermodel',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationanswermodel',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.applicationsubmissionmodel'),
        ),
    ]
