# Generated by Django 5.2.10 on 2026-02-11 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_applicantmodel_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantmodel',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.applicationformmodel'),
        ),
        migrations.AlterField(
            model_name='applicationsubmissionmodel',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted')], default='Draft', max_length=100),
        ),
    ]
