# Generated by Django 5.2.10 on 2026-02-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmodel',
            name='club_id',
        ),
    ]
